datagrid:
    search-grid:
        source:
            type: search
        columns:
            entity:
                label: Item
                type: search-result
                template: ~
                frontend_type: string
#            url:
#                label: URL
#                type: callback
#                callable: ~
#                frontend_type: string

        properties: ~
        sorters: ~
        filters: ~
