parameters:
    oro_search.string_filter.class: Oro\Bundle\SearchBundle\Filter\SearchStringFilter

services:
    oro_search.string_filter:
        class: %oro_search.string_filter.class%
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
        tags:
            - { name: oro_search.extension.search_filter.filter, type: string, datasource: search }
