placeholders:
  top_block:
    label: test block
    items:
      block_1: ~
      block2:
        order: 10

items:
  block_1:
    template: OroUIBundle::test.html.twig
  block2:
    action: OroSearchBundle:Search:searchBar
