parameters:
    oro_search.index.class:           Oro\Bundle\SearchBundle\Engine\Indexer
    oro_search.index_listener.class:  Oro\Bundle\SearchBundle\EventListener\IndexListener
    oro_search.twig_extension.class:  Oro\Bundle\SearchBundle\Twig\OroSearchExtension
    oro_search.mapper.class:          Oro\Bundle\SearchBundle\Engine\ObjectMapper
    oro_search.result_provider.class: Oro\Bundle\SearchBundle\Provider\ResultProvider

services:
    oro_search.index:
        class:        %oro_search.index.class%
        arguments:    [@doctrine.orm.entity_manager, @oro_search.search.engine, @translator, @oro_search.mapper]

    oro_search.index_listener:
        class:        %oro_search.index_listener.class%
        arguments:    [@service_container, %oro_search.entities_config%]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preRemove }

    oro_search.twig.search_extension:
        class:        %oro_search.twig_extension.class%
        tags:
            - { name: twig.extension }

    oro_search.mapper:
        class:        %oro_search.mapper.class%
        arguments:    [@service_container, @translator, %oro_search.entities_config%]

    oro_search.result_provider:
        class:        %oro_search.result_provider.class%
        arguments:    [@oro_search.index]
