parameters:
    oro_search.index.class:                               Oro\Bundle\SearchBundle\Engine\Indexer
    oro_search.index_listener.class:                      Oro\Bundle\SearchBundle\EventListener\IndexListener
    oro_search.twig_extension.class:                      Oro\Bundle\SearchBundle\Twig\OroSearchExtension
    oro_search.mapper.class:                              Oro\Bundle\SearchBundle\Engine\ObjectMapper
    oro_search.provider.result_statistics_provider.class: Oro\Bundle\SearchBundle\Provider\ResultStatisticsProvider
    oro_search.formatter.result_formatter.class:          Oro\Bundle\SearchBundle\Formatter\ResultFormatter

services:
    oro_search.index:
        class:                        %oro_search.index.class%
        arguments:                    ["@doctrine.orm.entity_manager", "@oro_search.search.engine", "@oro_search.mapper"]

    oro_search.index_listener:
        class:                        %oro_search.index_listener.class%
        arguments:                    ["@service_container", %oro_search.realtime_update%, %oro_search.entities_config%]
        tags:
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postPersist }

    oro_search.twig.search_extension:
        class:                        %oro_search.twig_extension.class%
        tags:
            - { name: twig.extension }

    oro_search.mapper:
        class:                        %oro_search.mapper.class%
        arguments:                    ["@service_container", %oro_search.entities_config%]

    oro_search.provider.result_statistics_provider:
        class:                        %oro_search.provider.result_statistics_provider.class%
        arguments:                    ["@oro_search.index"]

    oro_search.formatter.result_formatter:
        class:                        %oro_search.formatter.result_formatter.class%
        arguments:                    ["@doctrine.orm.entity_manager"]
