parameters:
    oro_search.engine.class: Oro\Bundle\SearchBundle\Engine\Orm
    oro_search.drivers:
        pdo_mysql: Oro\Bundle\SearchBundle\Engine\Orm\PdoMysql
        pdo_pgsql: Oro\Bundle\SearchBundle\Engine\Orm\PdoPgsql

services:
    oro_search.search.engine:
        class: %oro_search.engine.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @event_dispatcher
            - @service_container
            - @oro_search.mapper
            - %oro_search.log_queries%
