doctrine:
    orm:
        entity_managers:
            search:
                connection: default
                mappings:
                    OroSearchBundle:
                        mapping:   true
                        is_bundle: true
                metadata_cache_driver:
                    type: service
                    id:   oro_search.cache.doctrine_metadata
